x-api-adonisjs-env: &api-adonisjs-env
  HOST: 0.0.0.0
  PORT: 8000
  LOG_LEVEL: info
  NODE_ENV: production
  DB_HOST: api-postgres
  DB_PORT: 5432
  DB_USER: adonisjs
  DB_DATABASE: app

x-api-postgres-env: &api-postgres-env
  POSTGRES_DB: app
  POSTGRES_USER: adonisjs
  POSTGRES_PASSWORD_FILE: /run/secrets/root_pass

services:
  api-adonisjs:
    build:
      context: ..
      dockerfile: packages/backend/docker/dockerfile.local
    image: kdongs-api-adonisjs
    container_name: kdongs-api-adonisjs
    restart: unless-stopped
    depends_on:
      api-postgres:
        condition: service_healthy
    environment:
      <<: *api-adonisjs-env
    secrets:
      - root_pass
    ports:
      - '8000:3333'
    networks:
      - api-network
    profiles:
      - full
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.4G'

  api-postgres:
    image: postgres:16-alpine
    container_name: api-postgres
    restart: unless-stopped
    environment:
      <<: *api-postgres-env
    secrets:
      - root_pass
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '8001:5432'
    networks:
      - api-network
    volumes:
      - ./postgres/init/local.init-setup.sh:/docker-entrypoint-initdb.d/init-setup.sh
      - api-postgres:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c pg_stat_statements.max=10000
      -c track_activity_query_size=2048
    profiles:
      - db-only
      - full
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '1G'

secrets:
  root_pass:
    file: ./secrets/postgres_root_pass.txt

networks:
  api-network:
    driver: bridge

volumes:
  api-adonisjs:
    driver: local
  api-postgres:
    driver: local
